version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
  #    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html

    networks:
      - app-network

    ports:
      - '8080:80'

volumes:
  dbdata:
  wordpress:


networks:
  app-network:
    driver: bridge